### ISSUE TITLE
Filters seems not to be working

### ISSUE THREAD

**Issue by hhkaos** [esri-es/arcgis_websocket_server#18]
On [feature/RealTimeLayerListWidget](https://github.com/esri-es/arcgis_websocket_server/tree/feature/RealTimeLayerListWidget):

<img width="1279" alt="filters_not-working" src="https://user-images.githubusercontent.com/826965/58117184-491c1e80-7bfe-11e9-9478-193eae64f703.png">

Just run an http-server and open [example/widget.html](https://github.com/esri-es/arcgis_websocket_server/blob/feature/RealTimeLayerListWidget/example/widget.html).

You just need to update the service url on [line 77](https://github.com/esri-es/arcgis_websocket_server/blob/feature/RealTimeLayerListWidget/example/widget.html#L77)

You can set a new filter on [line 88](https://github.com/esri-es/arcgis_websocket_server/blob/feature/RealTimeLayerListWidget/example/widget.html#L88)

Thanks!

**Comment by ntkog** [comment]
Fixed on [#20](https://github.com/esri-es/arcgis_websocket_server/commit/28859c67f05d71593ed86a29abc986871da9ca09)
