### ISSUE TITLE
Dynamic service description

### ISSUE THREAD

**Issue by hhkaos** [esri-es/arcgis_websocket_server#5]
Build [service.js](https://github.com/esri-es/arcgis_websocket_server/blob/master/mock/service.js) dynamically and set `Fields, fieldID, etc` time info, even drawing info dynamically.

**Comment by ntkog** [comment]
It wold nice to check beforehand ws connection. If it's able to connect , then retrieve the first payload, and pass an object to [fill function](https://github.com/esri-es/arcgis_websocket_server/blob/master/mock/service.js#L160) , for building dynamically the StreamServer according to real data.

**Comment by ntkog** [comment]
Done! all the work it's now merged to master.
