### ISSUE TITLE
Not working for v3.x and <v4.8

### ISSUE THREAD

**Issue by hhkaos** [esri-es/arcgis_websocket_server#8]
Not v3.x and < v4.8 are not working xD. When fixed #3 this was broken ^_^

**Comment by ntkog** [comment]
We also have to enable StreamServer Layer import on AGOL .

**Comment by ntkog** [comment]
Now it could be used in AGOL again 👍 
I've implemented a rudimentary mechanism to skip "the challenge" on [doChallenge](https://github.com/esri-es/arcgis_websocket_server/blob/master/streamserver/streamserver_simple.js#L15)

**Comment by hhkaos** [comment]
Fixing on [this commit](https://github.com/esri-es/arcgis_websocket_server/commit/13b00b2f70b74463d195ac9dbffdf60c63705afe)
